### ISSUE TITLE
How to control "Maximum product count hit 10000, stopping reaction early"

### ISSUE THREAD

**Issue by jlaw9** [tyo-nu/MINE-Database#40]
**What is your question?**

I keep getting the warning message "Maximum product count hit 10000, stopping reaction early...", but I can't find where in the code this warning message is coming from. Can you help me find it?

Also, this limit appears to be for a single compound, is that right?

**Comment by KShebek** [comment]
Hi, sorry for the delay.

This is actually for a **single compound** for a **single reaction** rule. So a compound can have up to 10,000 * n_rules maximum reactions total in theory. I will open an issue getting someone to update this as an option to the user, but in the meantime you can edit it here.

https://github.com/tyo-nu/MINE-Database/blob/master/minedatabase/reactions.py#L170

Kevin

**Comment by jlaw9** [comment]
Makes sense. Thank you @KShebek!
